services:

  web:
    build: .
    container_name: orewa-web

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - ./media:/app/media

    environment:
      MONGO_URI: mongodb://mongo:27017

    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: orewa-mongo

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: